config/routes.rb
Rails.application.routes.draw do

  resources :facturacions

  resources :novedades

  resources :nominas

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :users
resources :novedades

  resources :cargos

  resources :inventarios

  resources :cotizacions

  resources :clientes do 
     resources :cotizacions
  end

  resources :empleados do
      resources :experiencia
      resources :estudios
      resources :nominas
  end

  resources :experiencia

  resources :estudios

  resources :estados

  resources :cargos

  resources :user_sessions 
  resources :users 
 
  get 'login', to:'user_sessions#new', :as => :login 
  get 'logout', to: 'user_sessions#destroy', :as => :logout 

  get 'allcotizacions/', to: 'cotizacions#allcotizacions', as: 'cotizaciones'

  root 'user_sessions#new#index'

  

   
end

app/models/novedade.rb
class Novedade < ActiveRecord::Base
	belongs_to :empleado
	
	
def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |novedade|
      csv << novedade.attributes.values_at(*column_names)
    end
  end
end
end

app/controllers/novedades_controller.rb
class NovedadesController < ApplicationController
  before_action :set_novedade, only: [:show, :edit, :update, :destroy, :index, :new, :create]

  # GET /novedades
  # GET /novedades.json

def index
 
 @novedades = @empleado.novedades.all
 respond_to do |format|
    format.html
    format.csv { send_data @novedades.to_csv }
    format.xls # { send_data @novedades.to_csv(col_sep: "\t") }
  end
end

def lista_novedades
  @empleados = Empleado.all
    
   respond_to do |format|
      format.html
      format.csv { send_data @novedades.to_csv }
      format.xls # { send_data @novedades.to_csv(col_sep: "\t") }
    end
end
  # GET /novedades/1
  # GET /novedades/1.json
  def show
  end

  # GET /novedades/new
  def new
    @novedade = Novedade.new
  end

  # GET /novedades/1/edit
  def edit
  end

  # POST /novedades
  # POST /novedades.json
  def create
    @novedade = Novedade.new(novedade_params)
    @novedade.empleado_id = @empleado.id
    respond_to do |format|
      if @novedade.save
        format.html { redirect_to empleado_novedades_path(@empleado), notice: 'Novedade was successfully created.' }
        format.json { render :show, status: :created, location: @novedade }
      else
        format.html { render :new }
        format.json { render json: @novedade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /novedades/1
  # PATCH/PUT /novedades/1.json
  def update
    respond_to do |format|
      if @novedade.update(novedade_params)
        format.html { redirect_to empleado_novedades_path(@empleado), notice: 'Novedade was successfully updated.' }
        format.json { render :show, status: :ok, location: @novedade }
      else
        format.html { render :edit }
        format.json { render json: @novedade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /novedades/1
  # DELETE /novedades/1.json
  def destroy
    @novedade.destroy
    respond_to do |format|
      format.html { redirect_to empleado_novedades_url(@empleado), notice: 'Novedade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_novedade
      @empleado = Empleado.find(params[:empleado_id])
      @novedade = Novedade.find(params[:id])if params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def novedade_params
      params.require(:novedade).permit(:iniciovacaciones, :finvacaciones, :prendasrealizadas, :valorprenda, :sueldobasico, :primalegal, :festivostrabajados, :diasnotrabajados, :horasnotrabajadas, :empleado_id)
    end
end

app/helpers/novedades_helper.rb
module NovedadesHelper
 def sumas(prendasrealizadas, valorprenda) 
 	prendasrealizadas * valorprenda.to_i 
 end

 def mostrar_estado(estado) 
	     if estado
			"<p class='label label-success'>HABILITADO</p>".html_safe 
			else 
			"<p class='label label-danger'>INABILITADO</p>".html_safe 
	     end 
    end 

    
    def estado(estado) 
	     if estado
			"<p class='label label-success'>HABILITADO</p>".html_safe 
			else 
			"<p class='label label-danger'>INABILITADO</p>".html_safe 
	     end 
    end  


end

app/views/novedades/_form.html.erb
<%= simple_form_for [@empleado,@novedade], :html => { :class => 'form-horizontal' } do |f| %>
  <% if @novedade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@novedade.errors.count, "error") %> prohibited this novedade from being saved:</h2>

      <ul>
      <% @novedade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :iniciovacaciones %><br>
    <%= f.date_select :iniciovacaciones %>
  </div>
  <div class="field">
    <%= f.label :finvacaciones %><br>
    <%= f.date_select :finvacaciones %>
  </div>
  <div class="field">
    <%= f.label :prendasrealizadas %><br>
    <%= f.number_field :prendasrealizadas %>
  </div>
  <div class="field">
    <%= f.label :valorprenda %><br>
    <%= f.number_field :valorprenda %>
  </div>
  <div class="field">
    <%= f.label :sueldobasico %><br>
    <%= f.number_field :sueldobasico %>
  </div>
  <div class="field">
    <%= f.label :primalegal %><br>
    <%= f.number_field :primalegal %>
  </div>
  <div class="field">
    <%= f.label :festivostrabajados %><br>
    <%= f.number_field :festivostrabajados %>
  </div>
  <div class="field">
    <%= f.label :diasnotrabajados %><br>
    <%= f.number_field :diasnotrabajados %>
  </div>
  <div class="field">
    <%= f.label :horasnotrabajadas %><br>
    <%= f.number_field :horasnotrabajadas %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/novedades/edit.html.erb
<h1>Editing novedade</h1>

<%= render 'form' %>

<%= link_to 'Show', empleado_novedade_path(@empleado,@novedade) %> |
<%= link_to 'Back', empleado_novedades_path(@empleado) %>

app/views/novedades/index.html.erb
<h1>Novedad del Empleado </h1>

<table>
  <thead>
    <tr>
      <th>Iniciovacaciones</th>
      <th>Finvacaciones</th>
      <th>Prendasrealizadas</th>
      <th>Valorprenda</th>
      <th>Total</th>
      <th>Sueldobasico</th>
      <th>Primalegal</th>
      <th>Festivostrabajados</th>
      <th>Diasnotrabajados</th>
      <th>Horasnotrabajadas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @novedades.each do |novedade| %>
      <tr>
        <td><%= novedade.iniciovacaciones %></td>
        <td><%= novedade.finvacaciones %></td>
        <td><%= novedade.prendasrealizadas %></td>
        <td><%= novedade.valorprenda %></td>
        <td><%= sumas(novedade.prendasrealizadas, novedade.valorprenda) %></td>
        <td><%= novedade.sueldobasico %></td>
        <td><%= novedade.primalegal %></td>
        <td><%= novedade.festivostrabajados %></td>
        <td><%= novedade.diasnotrabajados %></td>
        <td><%= novedade.horasnotrabajadas %></td>
        <td><%= link_to 'Ver', empleado_novedade_path(@empleado,novedade) %></td>
        <td><%= link_to 'Editar', edit_empleado_novedade_path(@empleado,novedade)%></td>
        <td><%= link_to 'Eliminar', empleado_novedade_path(@empleado,novedade), method: :delete, data: { confirm: 'Esta Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Novedad', new_empleado_novedade_path(@empleado) %>



<p>
  Download:
  <%= link_to "CSV", empleado_novedades_path(format: "csv") %> |
  <%= link_to "Excel", empleado_novedades_path(format: "xls") %>
</p>

app/views/novedades/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="integer">iniciovacaciones</Data></Cell>
        <Cell><Data ss:Type="integer">Finvacaciones</Data></Cell>
        <Cell><Data ss:Type="integer">Prendasrealizadas</Data></Cell>
        <Cell><Data ss:Type="integer">Valorprenda</Data></Cell>
        <Cell><Data ss:Type="integer">Sueldobasico</Data></Cell>
        <Cell><Data ss:Type="integer">Festivostrabajados</Data></Cell>
        <Cell><Data ss:Type="integer">Diasnotrabajados</Data></Cell>
        <Cell><Data ss:Type="integer">Horasnotrabajadas</Data></Cell>
        <Cell><Data ss:Type="integer">Valor Total De Prendas</Data></Cell>


      </Row>
    <% @novedades.each do |novedade| %>
      <Row>
        <Cell><Data ss:Type="integer"><%= novedade.iniciovacaciones %></Data></Cell>
        <Cell><Data ss:Type="integer"><%= novedade.finvacaciones %></Data></Cell>
        <Cell><Data ss:Type="integer"><%= novedade.prendasrealizadas %></Data></Cell>
        <Cell><Data ss:Type="integer"><%= novedade.valorprenda %></Data></Cell>
        <Cell><Data ss:Type="integer"><%= novedade.sueldobasico %></Data></Cell>
        <Cell><Data ss:Type="integer"><%= novedade.festivostrabajados %></Data></Cell>
        <Cell><Data ss:Type="integer"><%= novedade.diasnotrabajados %></Data></Cell>
        <Cell><Data ss:Type="integer"><%= novedade.horasnotrabajadas %></Data></Cell>
        <Cell><Data ss:Type="integer"><%= suma(novedade.prendasrealizadas, novedade.valorprenda) %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/novedades/lista_novedades.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Empleado</Data></Cell>
        <Cell><Data ss:Type="String">Documento</Data></Cell>
        <Cell><Data ss:Type="integer">Vacaciones</Data></Cell>
        <Cell><Data ss:Type="integer">Fin_Vacaciones</Data></Cell>
        <Cell><Data ss:Type="integer">Prendas_Realizadas</Data></Cell>
        <Cell><Data ss:Type="integer">Valor_Prenda</Data></Cell>
        <Cell><Data ss:Type="integer">Sueldo</Data></Cell>
        <Cell><Data ss:Type="integer">Festivos</Data></Cell>
        <Cell><Data ss:Type="integer">Dias_No_Trabajados</Data></Cell>
        <Cell><Data ss:Type="integer">Horas_No_Trabajadas</Data></Cell>
        <Cell><Data ss:Type="integer">Valor Total De Prendas</Data></Cell>
        <Cell><Data ss:Type="integer">Estado</Data></Cell>

      </Row>
    <% @empleados.each do |empleado|
        @novedades = empleado.novedades.all      
        unless @novedades.first.nil?

           @novedades.each do |novedade| %>

            <Row>
              <Cell><Data ss:Type="String"><%= empleado.nombre %></Data></Cell>
              <Cell><Data ss:Type="String"><%= empleado.doc %></Data></Cell>
              <Cell><Data ss:Type="integer"><%= novedade.iniciovacaciones %></Data></Cell>
              <Cell><Data ss:Type="integer"><%= novedade.finvacaciones %></Data></Cell>
              <Cell><Data ss:Type="integer"><%= novedade.prendasrealizadas %></Data></Cell>
              <Cell><Data ss:Type="integer"><%= novedade.valorprenda %></Data></Cell>
              <Cell><Data ss:Type="integer"><%= novedade.sueldobasico %></Data></Cell>
              <Cell><Data ss:Type="integer"><%= novedade.festivostrabajados %></Data></Cell>
              <Cell><Data ss:Type="integer"><%= novedade.diasnotrabajados %></Data></Cell>
              <Cell><Data ss:Type="integer"><%= novedade.horasnotrabajadas %></Data></Cell>
              <Cell><Data ss:Type="integer"><%= suma(novedade.prendasrealizadas, novedade.valorprenda) %></Data></Cell>
              <Cell><Data ss:Type="integer"><%=mostrar_estado(empleado.activo) %></Data></Cell>
            </Row>
          <% end %>
      <%  end  %>
  <%  end  %>    
    </Table>
  </Worksheet>
</Workbook>

app/views/novedades/new.html.erb
<h1>Nueva novedad</h1>

<%= render 'form' %>

<%= link_to 'atras', novedades_path %>

app/views/novedades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Iniciovacaciones:</strong>
  <%= @novedade.iniciovacaciones %>
</p>

<p>
  <strong>Finvacaciones:</strong>
  <%= @novedade.finvacaciones %>
</p>

<p>
  <strong>Prendasrealizadas:</strong>
  <%= @novedade.prendasrealizadas %>
</p>

<p>
  <strong>Valorprenda:</strong>
  <%= @novedade.valorprenda %>
</p>

<p>
  <strong>Sueldobasico:</strong>
  <%= @novedade.sueldobasico %>
</p>

<p>
  <strong>Primalegal:</strong>
  <%= @novedade.primalegal %>
</p>

<p>
  <strong>Festivostrabajados:</strong>
  <%= @novedade.festivostrabajados %>
</p>

<p>
  <strong>Diasnotrabajados:</strong>
  <%= @novedade.diasnotrabajados %>
</p>

<p>
  <strong>Horasnotrabajadas:</strong>
  <%= @novedade.horasnotrabajadas %>
</p>

<%= link_to 'Edit', edit_empleado_novedade_path(@empleado,@novedade) %> |
<%= link_to 'Back', empleado_novedades_path(@empleado) %>