config/routes.rb
Rails.application.routes.draw do

  resources :facturacions

  resources :novedades

  resources :nominas

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :users
resources :novedades

  resources :cargos

  resources :inventarios

  resources :cotizacions

  resources :clientes do 
     resources :cotizacions
  end

  resources :empleados do
      resources :experiencia
      resources :estudios
      resources :nominas
  end

  resources :experiencia

  resources :estudios

  resources :estados

  resources :cargos

  resources :user_sessions 
  resources :users 
 
  get 'login', to:'user_sessions#new', :as => :login 
  get 'logout', to: 'user_sessions#destroy', :as => :logout 

  get 'allcotizacions/', to: 'cotizacions#allcotizacions', as: 'cotizaciones'

  root 'user_sessions#new#index'

  

   
end

app/models/cotizacion.rb
class Cotizacion < ActiveRecord::Base

	belongs_to :cliente
	has_many :facturacions


	# Validar que los atributos sean obligatorios
	validates :cliente_id, :presence => true
	validates :producto, :presence => true
	validates :descripcion, :presence => true
	validates :cantidad, :presence => true
	validates :precio, :presence => true
	validates :iva, :presence => true
	validates :subtotal, :presence => true
	validates :total, :presence => true
	validates :estado, :presence => true
	

	def self.search(search, page) where(['upper(id) like ?', 
		"%#{search}%".upcase]).paginate(page: page, per_page: 5).order("id") 
	end 
	
	

end

app/controllers/cotizacions_controller.rb
class CotizacionsController < ApplicationController

  before_action :set_cotizacion, except: [:allcotizacions]

  def index
      @cotizacions = @cliente.cotizacions.search(params[:search], params[:page]) 
  end

  def show
   @cotizacion = Cotizacion.find(params[:id])
    respond_to do |format|
    format.html
    format.pdf do
    pdf = CotizacionPdf.new(@cotizacion)
    send_data pdf.render, filename: "cotizacion_#{@cotizacion_number}.pdf",
    type: "application/pdf",
    disposition: "inline"
  end
end
  end

  def new
      @cotizacion = Cotizacion.new
      @cotizacion.cliente_id = @cliente.id
  end

  def edit
  end

  def create
    @cotizacion = Cotizacion.new(cotizacion_params)
    @cotizacion.cliente_id = @cliente.id 

    respond_to do |format|
      if @cotizacion.save
        format.html { redirect_to cliente_cotizacions_path(@cliente), notice: 'Cotizacion was successfully created.' }
        format.json { render :show, status: :created, location: @cotizacion }
      else
        format.html { render :new }
        format.json { render json: @cotizacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cotizacions/1
  # PATCH/PUT /cotizacions/1.json
  def update
    respond_to do |format|
      if @cotizacion.update(cotizacion_params)
        format.html { redirect_to cliente_cotizacions_path(@cliente), notice: 'Cotizacion was successfully updated.' }
        format.json { render :show, status: :ok, location: @cotizacion }
      else
        format.html { render :edit }
        format.json { render json: @cotizacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cotizacions/1
  # DELETE /cotizacions/1.json
  def destroy
    @cotizacion.destroy
    respond_to do |format|
      format.html { redirect_to cliente_cotizacions_url(@cliente), notice: 'Cotizacion was successfully destroyed.' }

      format.json { head :no_content }
    end
  end

  def allcotizacions
    @cotizacions = Cotizacion.search(params[:search], params[:page]) 
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
  
  def set_cotizacion 
      @cliente = Cliente.find(params[:cliente_id])
      @cotizacion = Cotizacion.find(params[:id]) if params[:id] 
  end 

    # Never trust parameters from the scary internet, only allow the white list through.
    def cotizacion_params
      params.require(:cotizacion).permit(:cliente_id, :producto, :descripcion, 
                                         :cantidad, :precio, :iva, :subtotal, :total, :estado, :fch_creacion, :fch_final)
    end
end

app/helpers/cotizacions_helper.rb
module CotizacionsHelper
	def mostrar_estado(estado) 
	     if estado 
			"Aprobado" 
		 else 
			"No Aprobado" 
	     end 
	end 
end

app/views/cotizacions/_form.html.erb
<%= form_for [@cliente,@cotizacion] do |f| %>
  <% if @cotizacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cotizacion.errors.count, "error") %> prohibited this cotizacion from being saved:</h2>

      <ul>
      <% @cotizacion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :fch_creacion %><br>
    <%= f.date_select  :fch_creacion %>
  </div>
  <div class="field">
    <%= f.label :fch_final %><br>
    <%= f.date_select  :fch_final %>
  </div>
  <div class="field">
    <%= f.label :producto %><br>
    <%= f.text_field :producto %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.text_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.number_field :precio %>
  </div>
  <div class="field">
    <%= f.label :iva %><br>
    <%= f.number_field :iva %>
  </div>
  <div class="field">
    <%= f.label :subtotal %><br>
    <%= f.number_field :subtotal %>
  </div>
  <div class="field">
    <%= f.label :total %><br>
    <%= f.number_field :total %>
  </div>

  <div class="field"> 
  Aprobado: <%= f.radio_button(:estado, true) %> 
  No aprobado: <%= f.radio_button(:estado, false) %> 
</div> 
  <div class="actions">
    <%= f.submit %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), 
    cliente_cotizacions_path(@cliente), :class => 'btn' %> 
  </div>


<% end %>

app/views/cotizacions/allcotizacions.html.erb
<center><h1 class="alert alert-info">Listado de cotizaciones</h1></center>





<table class="table table-condensed">
  <thead>
    <tr>
      <th class="warning">ID</th>
      <th class="success">Cliente</th>
      <th class="danger">Empresa</th>
      <th class="info">Producto</th>
      <th class="warning">Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cotizacions.each do |cotizacion| %>
      <tr>
        <td class="warning"><%= cotizacion.id %></td>
        <td class="success"><%= cotizacion.cliente.nombre %></td>
        <td class="danger"><%= cotizacion.cliente.empresa %></td>
        <td class="info"><%= cotizacion.producto %></td>
        <td class="warning"><%= cotizacion.estado %></td>
        <td><%= link_to 'Ver', cliente_cotizacion_path(cotizacion.cliente,cotizacion), class: "btn btn-primary btn-xs" %></td>
        <td><%= link_to 'Editar', edit_cliente_cotizacion_path(cotizacion.cliente,cotizacion), class: "btn btn-primary btn-xs" %></td>
        <td><%= link_to 'Eliminar', cliente_cotizacion_path(cotizacion.cliente,cotizacion) , method: :delete, data: { confirm: 'Esta seguro?' }, class: "btn btn-warning btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



<%= will_paginate @cotizacions, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente 
&raquo;' %> 
<br> 
Cotizaciones: <%= @cotizacions.count %>

app/views/cotizacions/edit.html.erb
<h1>Editar cotizacion</h1>

<%= render 'form' %>

<%= link_to 'Ver', @cotizacion %> |
<%= link_to 'Atras', cliente_cotizacions_path(@cliente) %>

app/views/cotizacions/index.html.erb
<center><h1 class="alert alert-info">Cotizaciones de: <%= @cliente.nombre %></h1></center>
	<table class="table table-condensed">
		<thead>
			<tr>
			<th class="warning">Cliente</th>
			<th class="success">Empresa</th>
			<th class="danger">Producto</th>
			<th class="info">Estado</th>
			<th colspan="3"></th>
			</tr>
		</thead>
		<tbody>
			<% @cotizacions.each do |cotizacion| %>
			<tr>
			<td class="warning"><%= cotizacion.cliente.nombre %></td>
			<td class="success"><%= cotizacion.cliente.empresa %></td>
			<td class="danger"><%= cotizacion.producto %></td>
			<td class="info"><%= cotizacion.estado %></td>
			
			<td><%= link_to 'Ver', cliente_cotizacion_path(@cliente,cotizacion), class: "btn btn-primary btn-xs" %></td>
			<td><%= link_to 'Editar', edit_cliente_cotizacion_path(@cliente,cotizacion), class: "btn btn-primary btn-xs" %></td>
			<td><%= link_to 'Eliminar', cliente_cotizacion_path(@cliente,cotizacion) , method: :delete, data: { confirm: 'Esta seguro?' }, class: "btn btn-primary btn-xs" %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
<br>
<%= link_to t('.new', :default => t("helpers.links.nuevo")),
new_cliente_cotizacion_path(@cliente),
:class => 'btn btn­primary' %>
<%= will_paginate @cotizacions, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente
&raquo;' %>
<br>
Cotizaciones: <%= @cotizacions.count %>

app/views/cotizacions/new.html.erb
<h1>Cotizaciones: <%= @cliente.nombre %></h1>

<%= render 'form' %>

<%= link_to 'Atras', cotizacions_path %>

app/views/cotizacions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha de creacion:</strong>
  <%= @cotizacion.fch_creacion %>
</p>
<p>
  <strong>Fecha de entrega:</strong>
  <%= @cotizacion.fch_final %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @cotizacion.cliente.nombre %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @cotizacion.cliente.telefono %>
</p>

<p>
  <strong>Empresa:</strong>
  <%= @cotizacion.cliente.empresa %>
</p>

<p>
  <strong>Nit:</strong>
  <%= @cotizacion.cliente.nit %>
</p>

<p>
  <strong>Producto:</strong>
  <%= @cotizacion.producto %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @cotizacion.descripcion %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @cotizacion.cantidad %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @cotizacion.precio %>
</p>

<p>
  <strong>Iva:</strong>
  <%= @cotizacion.iva %>
</p>

<p>
  <strong>Subtotal:</strong>
  <%= @cotizacion.subtotal %>
</p>

<p>
  <strong>Total:</strong>
  <%= @cotizacion.total %>
</p>

<p> 
<strong>Estado:</strong> 
<%= mostrar_estado(@cotizacion.estado) %> 
</p> 

<%= link_to 'Editar', edit_cotizacion_path(@cotizacion) %> |
<%= link_to 'Atras', cliente_cotizacions_path(@cliente) %>

<p><%= link_to 'Generar (PDF)', cotizacion_path(@cotizacion, format: 'pdf')%></P>