config/routes.rb
Rails.application.routes.draw do

  resources :facturacions

  resources :novedades

  resources :nominas

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :users
resources :novedades

  resources :cargos

  resources :inventarios

  resources :cotizacions

  resources :clientes do 
     resources :cotizacions
  end

  resources :empleados do
      resources :experiencia
      resources :estudios
      resources :nominas
  end

  resources :experiencia

  resources :estudios

  resources :estados

  resources :cargos

  resources :user_sessions 
  resources :users 
 
  get 'login', to:'user_sessions#new', :as => :login 
  get 'logout', to: 'user_sessions#destroy', :as => :logout 

  get 'allcotizacions/', to: 'cotizacions#allcotizacions', as: 'cotizaciones'

  root 'user_sessions#new#index'

  

   
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
	has_many :novedades

  belongs_to :estado
  belongs_to :nomina 
  belongs_to :cargo

  

  # Validar que los atributos sean obligatorios
	validates :nombre, :presence => true
	validates :estado_id, :presence => true
	validates :direccion, :presence => true
	validates :barrio, :presence => true
	validates :ciudad, :presence => true
	validates :celular, :presence => true
	validates :correo, :presence => true
	validates :fchinicio, :presence => true
	validates :fchfinal, :presence => true
	validates :ref, :presence => true
	validates :telref, :presence => true
	# validar que un atributos unicos
	validates :doc, uniqueness: { message: "Ya Existe" }
	validates :correo, uniqueness: { message: "No se puede Repetir" }
	validates :telefono, numericality: { message: "Debe ser solo Numeros" }
	validates :celular, numericality: { message: "Debe ser solo Numeros" }
	# validar formato de un correo
	validates :correo, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
	message: 'Formato no valido' }
			
	 	
def self.search(search, page)
	where(['upper(nombre) like ?',
	"%#{search}%".upcase]).paginate(page: page, per_page: 5).order("nombre")
 end

end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  before_action :set_empleado, only: [:show, :edit, :update, :destroy]

  # GET /empleados
  # GET /empleados.json
  def index
    @empleados = Empleado.search(params[:search], params[:page])
  end

  # GET /empleados/1
  # GET /empleados/1.json
  def show
  end

  # GET /empleados/new
  def new
    @empleado = Empleado.new
  end

  # GET /empleados/1/edit
  def edit
  end

  # POST /empleados
  # POST /empleados.json
  def create
    @empleado = Empleado.new(empleado_params)
    render action: :new unless @empleado.save
  end

  # PATCH/PUT /empleados/1
  # PATCH/PUT /empleados/1.json
  def update
    render action: :edit unless @empleado.update(empleado_params)
  end

  # DELETE /empleados/1
  # DELETE /empleados/1.json
  def destroy
    @empleado.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empleado
      @empleado = Empleado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empleado_params
      params.require(:empleado).permit(:nombre, :doc, :estado_id, :direccion, :barrio, :ciudad, :telefono, :celular, :correo, :genero, :fchinicio, :fchfinal, :cargo_id, :ref, :telref, :activo)
    end
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
	def mostrar_genero(genero)
     if genero 
		"Masculino"
		else
		"Femenino"
     end
end
	
	def mostrar_estado(estado) 
	     if estado
			"<p class='label label-success'>HABILITADO</p>".html_safe 
			else 
			"<p class='label label-danger'>INABILITADO</p>".html_safe 
	     end 
    end 

   	

end

app/views/empleados/_empleado.html.erb
<tr id=<%= "empleado_#{empleado.id}" %>> 

        <td class="warning"><%= empleado.nombre %></td>
        <td class="success"><%= empleado.doc %></td>
        <td class="danger"><%= empleado.cargo.nombre rescue nil %></td>
        
        <td><%= link_to 'Mostrar', empleado, remote: true, class: "btn btn-primary btn-xs" %></td> 
        <td><%= link_to 'Editar', edit_empleado_path(empleado), remote: true, class: "btn btn-primary btn-xs" %></td> 
        <td><%=  link_to   'Eliminar',   empleado,   method:   :delete,   data:   {   confirm:   'Esta   Seguro?' , remote: true}, class: "btn btn-warning btn-xs"%></td> 
</tr> 

app/views/empleados/_form.html.erb
<div class="formuemple">
<%=   simple_form_for(@empleado,   :html   =>   {   :class   =>   'form­horizontal',   remote:   true   }   )   do   |f|  %> 
  <% if @empleado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@empleado.errors.count, "error") %> prohibited this empleado from being saved:</h2>

      <ul>
      <% @empleado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

   <%= f.collection_select :cargo_id, Cargo.all, :id, :nombre, class: "form-control", prompt: "Cargo" %>
  </div>


  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :doc %><br>
    <%= f.text_field :doc %>
  </div>

 
   <div class="field">
   <%= f.collection_select :estado_id, Estado.all, :id, :name, class: "form-control", prompt: "Estado Civil" %>
  </div>


  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :barrio %><br>
    <%= f.text_field :barrio %>
  </div>
  <div class="field">
    <%= f.label :ciudad %><br>
    <%= f.text_field :ciudad %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :celular %><br>
    <%= f.text_field :celular %>
  </div>
  <div class="field">
    <%= f.label :correo %><br>
    <%= f.text_field :correo %>
  </div>
  <div class="field">
    Masculino: <%= f.radio_button(:genero, true) %>
    Femenino: <%= f.radio_button(:genero, false) %>
</div>
  <div class="field">
    <%= f.label :fchinicio %><br>
    <%= f.date_select :fchinicio %>
  </div>
  <div class="field">
    <%= f.label :fchfinal %><br>
    <%= f.date_select :fchfinal %>
  </div>

  <div class="field">
    <%= f.label :ref %><br>
    <%= f.text_field :ref %>
  </div>
  <div class="field">
    <%= f.label :telreferencia %><br>
    <%= f.text_field :telref %>
  </div>

<div class="field">
    Estado:<br>
    Habilitado <%= f.radio_button(:activo, true) %>
    Inabilitado <%= f.radio_button(:activo, false) %>
</div>
  
  <div class="form­group"> 
  <div class="col­sm­offset­2 col­sm­10"> 


  <div class="actions">
    <%= f.submit "Guardar", :class => "btn btn­-info" %>
  </div>
<% end %>
</div>

app/views/empleados/_nomina.html.erb
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Documento</th>
      <th>Estado</th>
      <th>Crear - Novedades</th>
    </tr>
  </thead>

  <tbody> 
    <% @empleados.each do |empleado| %>
      <tr>
        <td ><%= empleado.nombre %></td>
        <td ><%= empleado.doc %></td>
        <td ><%= mostrar_estado(empleado.activo) %></td>
        <% if empleado.activo == false %>
           <td class="bg-danger">Novedad No Permitida</td>
        <% else %>
          <td ><%= link_to 'Registrar Novedad', empleado_novedades_path(empleado) %></td>
        <% end %>
    <% end %>

  </tbody> 
</table>

<br>


<center>Total de Empleados: <%= (@empleados.count) %><center>
<p>

  Download:
  <%= link_to "Excel", lista_novedades_path(format: "xls") %>
</p>

app/views/empleados/_show.html.erb
<div class='empleado'> 

  <p id="notice"><%= notice %></p>

  <p>
    <strong>Nombre:</strong>
    <%= @empleado.nombre %>
  </p>

  <p>
    <strong>Documento:</strong>
    <%= @empleado.doc %>
  </p>

  <p>
    <strong>Estado:</strong>
    <%= @empleado.estado.name %>
  </p>

  <p>
    <strong>Direccion:</strong>
    <%= @empleado.direccion %>
  </p>

  <p>
    <strong>Barrio:</strong>
    <%= @empleado.barrio %>
  </p>

  <p>
    <strong>Ciudad:</strong>
    <%= @empleado.ciudad %>
  </p>

  <p>
    <strong>Telefono:</strong>
    <%= @empleado.telefono %>
  </p>

  <p>
    <strong>Celular:</strong>
    <%= @empleado.celular %>
  </p>

  <p>
    <strong>Correo:</strong>
    <%= @empleado.correo %>
  </p>

  <p>
    <strong>Genero:</strong>
    <%= mostrar_genero(@empleado.genero) %>
  </p>

  <p>
    <strong>Fchinicio:</strong>
    <%= @empleado.fchinicio %>
  </p>

  <p>
    <strong>Fchfinal:</strong>
    <%= @empleado.fchfinal %>
  </p>

  <p>
    <strong>Cargo:</strong>
    <%= @empleado.cargo.nombre %>
  </p>

  <p>
    <strong>Referencia:</strong>
    <%= @empleado.ref %>
  </p>

  <p>
    <strong>Tel referencia:</strong>
    <%= @empleado.telref %>
  </p>

  <p>
  <strong>Estado:</strong>
  <%= mostrar_estado(@empleado.activo) %>
</p>

  <%= link_to 'Editar', edit_empleado_path(@empleado), remote: true, class: "btn btn-primary btn-xs" %> |
  <%= link_to 'Atras', empleados_path, class: "btn btn-success btn-xs" %>
</div>

app/views/empleados/create.js.erb
$('table tbody').append("<%= escape_javascript(render @empleado) %>") 
$.lazybox.close() 

app/views/empleados/destroy.js.erb
$.lazybox.close() 
$("table tr#empleado_<%= @empleado.id %>").remove(); 

app/views/empleados/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {klass: 'custom'}); 

app/views/empleados/index.html.erb
<center><h1 class="alert alert-info">Empleados</h1></center>

<%= form_tag empleados_path, :method => 'get' do %>
<% content_tag :label do %>
Buscar por nombre:
<%= text_field_tag :search, params[:search] %>
<%= submit_tag "Buscar", :nombre => nil %>
<% end %>
<% end %>


<table class="table table-condensed">
  <thead>
    <tr>
      <th class="warning">Nombre</th>
      <th class="success">Documento</th>
      <th class="danger">Cargo</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody> 
    <%= render @empleados %> 

  </tbody> 
</table>

<br>


<%= link_to 'Nuevo Empleado', new_empleado_path, remote: true , class: "btn btn-warning btn-xs"%> 
<br>

<%= will_paginate @empleados, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente &raquo;' %>
<br>

app/views/empleados/new.js.erb
$.lazybox("<%= j(render partial: 'form') %>", { onTop: false }); 

app/views/empleados/show.js.erb
$.lazybox("<%= j(render 'show') %>", {klass: 'sticker' }) 

app/views/empleados/update.js.erb
$('tr#empleado_<%= @empleado.id %>').replaceWith("<%= j(render @empleado) %>") 
$.lazybox.close() 