config/routes.rb
Rails.application.routes.draw do

  resources :facturacions

  resources :novedades

  resources :nominas

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :users
resources :novedades

  resources :cargos

  resources :inventarios

  resources :cotizacions

  resources :clientes do 
     resources :cotizacions
  end

  resources :empleados do
      resources :experiencia
      resources :estudios
      resources :nominas
  end

  resources :experiencia

  resources :estudios

  resources :estados

  resources :cargos

  resources :user_sessions 
  resources :users 
 
  get 'login', to:'user_sessions#new', :as => :login 
  get 'logout', to: 'user_sessions#destroy', :as => :logout 

  get 'allcotizacions/', to: 'cotizacions#allcotizacions', as: 'cotizaciones'

  root 'user_sessions#new#index'

  

   
end

app/models/inventario.rb
class Inventario < ActiveRecord::Base

	# Validar que los atributos sean obligatorios
	validates :productos, :presence => true
	validates :cantidad, :presence => true
	# Valida si un atributo es numerico
	validates :cantidad, numericality: true

end

app/controllers/inventarios_controller.rb
class InventariosController < ApplicationController
  before_action :set_inventario, only: [:show, :edit, :update, :destroy]

  # GET /inventarios
  # GET /inventarios.json
  def index
    @inventarios = Inventario.search(params[:search], params[:page]) 
  end

  # GET /inventarios/1
  # GET /inventarios/1.json
  def show
    @inventario = Inventario.find(params[:id])
    respond_to do |format|
    format.html
    format.pdf do
    pdf = InventarioPdf.new(@inventario)
    send_data pdf.render, filename: "Inventario_#{@inventario_number}.pdf",
    type: "application/pdf",
    disposition: "inline"
end
end
  end

  # GET /inventarios/new
  def new
    @inventario = Inventario.new
  end

  # GET /inventarios/1/edit
  def edit
  end

  # POST /inventarios
  # POST /inventarios.json
  def create
    @inventario = Inventario.new(inventario_params)

    respond_to do |format|
      if @inventario.save
        format.html { redirect_to @inventario, notice: 'Inventario was successfully created.' }
        format.json { render :show, status: :created, location: @inventario }
      else
        format.html { render :new }
        format.json { render json: @inventario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventarios/1
  # PATCH/PUT /inventarios/1.json
  def update
    respond_to do |format|
      if @inventario.update(inventario_params)
        format.html { redirect_to @inventario, notice: 'Inventario was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventario }
      else
        format.html { render :edit }
        format.json { render json: @inventario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventarios/1
  # DELETE /inventarios/1.json
  def destroy
    @inventario.destroy
    respond_to do |format|
      format.html { redirect_to inventarios_url, notice: 'Inventario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventario
      @inventario = Inventario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventario_params
      params.require(:inventario).permit(:productos, :cantidad, :valor)
    end
end

app/helpers/inventarios_helper.rb
module InventariosHelper
	def suma(cantidad, valor)
		res = valor * cantidad.to_i
		return res
		
	end
end

app/views/inventarios/_form.html.erb
<%= form_for(@inventario) do |f| %>
  <% if @inventario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventario.errors.count, "error") %> prohibited this inventario from being saved:</h2>

      <ul>
      <% @inventario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :producto %><br>
    <%= f.text_field :productos %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.text_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :valorUnitario %><br>
    <%= f.text_field :valor %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventarios/edit.html.erb
<h1>Editar </h1>

<%= render 'form' %>

<%= link_to 'Ver', @inventario, class: "btn btn-primary btn-xs" %> |
<%= link_to 'Atras', inventarios_path, class: "btn btn-primary btn-xs" %>

app/views/inventarios/index.html.erb
<center><h1 class="alert alert-info">Lista de inventarios</h1></center>



<%= form_tag inventarios_path, :method => 'get' do %> 
<% content_tag :label do %> 
Buscar por producto: 
<%= text_field_tag :search, params[:search] %> 
<%= submit_tag "Buscar", :productos => nil %> 
<% end %> 
<% end %> 

<table class="table table-condensed">
  <thead>
    <tr>
      <th class="info">Productos</th>
      <th class="success">Cantidad</th>
      <th class="danger">valor unitario</th>
      <th class="warning">Precio</th>
      <th class="success">Opciones</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody><% sum = 0 %>
    <% @inventarios.each do |inventario| %>
      <tr>
        <td class="info"><%= inventario.productos %></td>
        <td class="success"><%= inventario.cantidad %></td>
        <td class="danger"><%= inventario.valor %></td>
        <td class="warning"><%= suma(inventario.cantidad, inventario.valor) %></td>
        <%
         sum += suma(inventario.cantidad, inventario.valor) %>
        <td class="success"><%= link_to 'Ver', inventario, class: "btn btn-primary btn-xs" %></td>
        <td class="success"><%= link_to 'Editar', edit_inventario_path(inventario), class: "btn btn-primary btn-xs" %></td>
        <td class="success"><%= link_to 'Eliminar', inventario, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p>suma total: <%= sum.to_s%></p>

<br>

<%= link_to 'Nuevo Inventario', new_inventario_path, class: "btn btn-warning btn-xs" %>

<%= will_paginate @inventarios, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente 
&raquo;' %> 
<br> 
Inventarios: <%= @inventarios.count %> 

app/views/inventarios/new.html.erb
<h1>Nuevo inventario</h1>

<%= render 'form' %>

<%= link_to 'Atras', inventarios_path, class: "btn btn-primary btn-xs" %>

app/views/inventarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Productos:</strong>
  <%= @inventario.productos %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @inventario.cantidad %>
</p>

<p>
  <strong>valor:</strong>
  <%= @inventario.productos %>
</p>


<%= link_to 'Edit', edit_inventario_path(@inventario), class: "btn btn-primary btn-xs" %> |
<%= link_to 'Back', inventarios_path, class: "btn btn-primary btn-xs" %>

<p><%= link_to 'Generar (PDF)', inventario_path(@inventario, format: 'pdf'), class: "btn btn-primary btn-xs"%></P>